FROM docker.elastic.co/elasticsearch/elasticsearch:5.3.1
MAINTAINER ramtruely6@gmail.com
ADD config/jvm.options /usr/share/elasticsearch/config/
ADD config/elasticsearch.yml /usr/share/elasticsearch/config/
EXPOSE 9200
EXPOSE 9300

